@startuml BPMN_Approval_Workflow_UA
!theme plain

title Робочий Процес Схвалення Нагороди - Діаграма Діяльності

start

:Працівник подає нагороду;

:Система валідує подання;

if (Валідне?) then (так)
    :Створити запит на рецензування;
    :Визначити рівень нагороди;
    
    if (Рівень Нагороди?) then (Кафедра/Факультет)
        :Призначити Секретарю Факультету;
        
        :Секретар Факультету рецензує нагороду;
        :Перевірити документи;
        
        switch (Рішення Секретаря?)
        case (Схвалити)
            :Зафіксувати схвалення;
            :Опублікувати нагороду;
            :Повідомити працівника про схвалення;
            stop
        case (Відхилити)
            :Зафіксувати відхилення з причиною;
            :Повідомити працівника про відхилення;
            
            if (Повторне подання?) then (так)
                :Працівник редагує нагороду;
                :Скинути до чернетки;
            else (ні)
                stop
            endif
        case (Ескалювати)
            :Ескалювати до Декана;
            
            :Декан рецензує нагороду;
            
            if (Декан схвалює?) then (так)
                :Зафіксувати схвалення;
                :Опублікувати нагороду;
                :Повідомити працівника;
                stop
            else (ні)
                :Зафіксувати відхилення;
                :Повідомити працівника;
                stop
            endif
        endswitch
        
    else (Університет/Національний/Міжнародний)
        :Призначити Секретарю Факультету;
        :Секретар Факультету рецензує та рекомендує;
        :Передати Декану;
        
        :Декан рецензує та рекомендує;
        :Передати до Ректорату;
        
        :Ректорат рецензує;
        
        if (Ректор схвалює?) then (так)
            if (Секретар має повноваження?) then (так)
                :Секретар схвалює;
            else (ні)
                :Ескалювати до Ректора;
                :Ректор рецензує та схвалює;
            endif
            :Опублікувати нагороду;
            :Повідомити працівника про схвалення;
            stop
        else (ні)
            :Зафіксувати відхилення;
            :Повідомити працівника про відхилення;
            stop
        endif
    endif
    
else (ні)
    :Повернути помилки валідації;
    :Працівник виправляє помилки;
endif

stop

@enduml


