name: Feature Request
description: Suggest an enhancement for the project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: input
    id: phase
    attributes:
      label: Related Phase
      description: Which development phase would this enhancement affect?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?

  - type: textarea
    id: portfolio-value
    attributes:
      label: Portfolio Value
      description: How would this enhance the portfolio demonstration?
