package ua.edu.chnu.awards.audit.entity;

/**
 * Security events written to {@code audit_logs} by the application (table triggers write the CRUD ones).
 */
public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    ACCOUNT_LOCKED,
    LOGOUT,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET,
    EMAIL_VERIFIED,
    SECURITY_REVOKE,
    REGISTRATION_REPLACED,
    ACCESS_DENIED,
    ROLE_ASSIGNED,
    ROLE_REVOKED,
    DELEGATION_CREATED,
    DELEGATION_REVOKED,
    AWARD_SUBMITTED,
    REVIEW_CLAIMED,
    REVIEW_RELEASED,
    REVIEW_HANDED_OVER,
    REVIEW_TAKEN_OVER,
    PROFILE_UPDATED,
    EMAIL_CHANGE_REQUESTED,
    EMAIL_CHANGED,
    DATA_EXPORT,
    AUDIT_EXPORT,
    DOCUMENT_DOWNLOAD,
    DOCUMENT_REJECTED
}
